import { useMutation } from "convex/react";
import type { FunctionReference } from "convex/server";

/**
 * Expected reference for a custom "generateXUploadUrl" mutation
 * (the ones we created in convex/integrations/r2.ts:
 * generateCvUploadUrl, generateListingUploadUrl, generatePdpUploadUrl,
 * generatePdcUploadUrl...).
 *
 * It should take { contentType?: string } and return { url, key }.
 */
type GenerateUploadUrlFn = FunctionReference<
  "mutation",
  "public",
  { contentType?: string },
  { key: string; url: string }
>;

/**
 * Reference to the `syncMetadata` mutation generated by r2.clientApi().
 * It's the same one for every file type.
 */
type SyncMetadataFn = FunctionReference<
  "mutation",
  "public",
  { key: string },
  unknown
>;

interface UseTypedR2UploadOptions {
  /**
   * Accepted MIME type, used only for a client-side check before
   * uploading (the real enforcement should stay on the server /
   * bucket policy).
   */
  accept?: string;
}

/**
 * Generic hook to upload a file to R2 through a custom
 * "generateXUploadUrl" mutation (so the key is prefixed with a
 * logical folder: cv/, listing/, pdp/, pdc/...), instead of the
 * generic generateUploadUrl from clientApi() which puts everything
 * at the bucket root.
 *
 * Mirrors what useUploadFile from @convex-dev/r2/react does, but
 * with a key controlled on the server side.
 */
export function useTypedR2Upload(
  generateUploadUrl: GenerateUploadUrlFn,
  syncMetadata: SyncMetadataFn,
  options?: UseTypedR2UploadOptions,
) {
  const generateUrl = useMutation(generateUploadUrl);
  const sync = useMutation(syncMetadata);

  async function upload(file: File): Promise<string> {
    if (options?.accept && !file.type.match(options.accept)) {
      throw new Error(`File type not allowed: ${file.type}`);
    }

    // 1. Request a signed URL + a prefixed key (e.g. "cv/uuid.pdf")
    const { url, key } = await generateUrl({ contentType: file.type });

    // 2. Upload the file directly to R2 via the signed URL
    const res = await fetch(url, {
      method: "PUT",
      headers: { "Content-Type": file.type },
      body: file,
    });

    if (!res.ok) {
      throw new Error(`R2 upload failed: ${res.status} ${res.statusText}`);
    }

    // 3. Sync metadata back on the Convex side
    await sync({ key });

    return key;
  }

  return { upload };
}
