import { R2 } from "@convex-dev/r2";
import { v } from "convex/values";
import { components } from "../_generated/api";
import type { DataModel } from "../_generated/dataModel";
import { authComponent } from "../auth/auth";
import { authMutation, internalMutation, query } from "../functions";
import { throwForbidden, throwNotFound } from "../utils/errors";

export const r2 = new R2(components.r2);

/**
 * ⚠️ This function generated by clientApi() ALWAYS puts files at the
 * bucket root with a UUID as the key. It doesn't accept a custom key
 * (documented behavior of @convex-dev/r2). Keep it for generic use
 * cases, but for "typed" content (cv, listing, pdp, pdc...) use the
 * custom mutations below instead.
 */
export const { generateUploadUrl, syncMetadata } = r2.clientApi<DataModel>({
  checkUpload: async (ctx) => {
    const user = await authComponent.safeGetAuthUser(ctx);
    if (!user) {
      throwForbidden("Not authenticated");
    }
  },
  onUpload: async () => {
    // Post upload operations can go here
  },
});

/**
 * Builds a clean key: folder/uuid.extension
 */
function buildKey(folder: string, contentType?: string | null) {
  const ext = contentType?.split("/")[1] ?? "bin";
  return `${folder}/${crypto.randomUUID()}.${ext}`;
}

/**
 * Custom mutation to upload a CV: the key is forced into the "cv/"
 * folder.
 */
export const generateCvUploadUrl = authMutation({
  args: {
    contentType: v.optional(v.string()),
  },
  handler: async (_, { contentType }) => {
    const key = buildKey("cv", contentType);

    // r2.generateUploadUrl (instance method, NOT clientApi) accepts a
    // custom key as an argument. ⚠️ It already returns { key, url } —
    // do NOT wrap it again in { url: <that object>, key }.
    return await r2.generateUploadUrl(key);
  },
});

/**
 * Custom mutation to upload an image tied to a listing.
 */
export const generateListingUploadUrl = authMutation({
  args: {
    contentType: v.optional(v.string()),
  },
  handler: async (_, { contentType }) => {
    const key = buildKey("listing", contentType);
    return await r2.generateUploadUrl(key);
  },
});

/**
 * Custom mutation to upload a profile picture (pdp).
 */
export const generatePdpUploadUrl = authMutation({
  args: {
    contentType: v.optional(v.string()),
  },
  handler: async (_, { contentType }) => {
    const key = buildKey("pdp", contentType);
    return await r2.generateUploadUrl(key);
  },
});

/**
 * Custom mutation to upload a cover picture (pdc).
 */
export const generatePdcUploadUrl = authMutation({
  args: {
    contentType: v.optional(v.string()),
  },
  handler: async (_, { contentType }) => {
    const key = buildKey("pdc", contentType);
    return await r2.generateUploadUrl(key);
  },
});

/**
 * Internal mutation to delete an R2 object by its key.
 * Reusable from other mutations or actions.
 */
export const deleteR2Object = internalMutation({
  args: { key: v.string() },
  handler: async (ctx, { key }) => {
    await r2.deleteObject(ctx, key);
  },
});

/**
 * Public mutation: upload a new CV key and delete the old one from R2.
 * - Deletes old CV from R2 if user had one
 * - Patches the user record with the new CV key
 */
export const uploadCvAndDeleteOld = authMutation({
  args: {
    newCvKey: v.string(),
  },
  handler: async (ctx, { newCvKey }) => {
    const user = ctx.user;

    // Delete old CV from R2 if it exists
    if (user.cv) {
      await r2.deleteObject(ctx, user.cv);
    }

    // Update user's CV field with the new key
    await ctx.runMutation(components.betterAuth.users.updateUser, {
      id: user._id,
      patch: { cv: newCvKey },
    });
  },
});

/**
 * Public mutation: delete the user's CV from R2 and clear the field.
 */
export const deleteCv = authMutation({
  args: {},
  handler: async (ctx) => {
    const user = ctx.user;
    if (!user.cv) {
      throwNotFound("No CV to delete");
    }

    // Delete from R2
    await r2.deleteObject(ctx, user.cv);

    // Clear the CV field
    await ctx.runMutation(components.betterAuth.users.updateUser, {
      id: user._id,
      patch: { cv: null },
    });
  },
});

/**
 * Public query: get the URL for the user's CV.
 */
export const getCvUrl = query({
  args: {},
  handler: async (ctx) => {
    const user = await authComponent.safeGetAuthUser(ctx);
    if (!user || !user.cv) return null;
    return await r2.getUrl(user.cv);
  },
});
